# Generated by Django 3.2 on 2022-08-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_admin_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='photo',
            field=models.ImageField(default=False, upload_to='admin_images/'),
        ),
    ]
